### ISSUE TITLE
Unique ID missing, calling a service gives "unknown error", running core-2021.5.0 HA-OS

### ISSUE THREAD

**Issue by 50915091Mica** [nqkdev/home-assistant-vacuum-styj02ym#38]
Hi there, I have been swimming in waters I do not understand anymore, so please help.
I have set all as described, the entity and its values is there properly but only for "reading", cannot call a service, cannot use as automation.

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/config_validation.py:133
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:50:13 (1 occurrences)
Last logged: 12:50:13

[139909373028240] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 21, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 482, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1209, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 345, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 563, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1435, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 133, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
TypeError: sequence item 0: expected str instance, Optional found

**Comment by igorsantos07** [comment]
The ID is indeed missing, and the [FAQ it links to](https://www.home-assistant.io/faq/unique_id/) kinda says the issue is with the integration?

It doesn't seem possible to try out the device with Developer Tools > Services > Vacuum: Locate, for instance. However, I was able to make it run via the new Dashboard box that appeared.
